/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Edgar
 */
public class ViewCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public ViewCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_titulo = new javax.swing.JLabel();
        jl_numero1 = new javax.swing.JLabel();
        jl_numero2 = new javax.swing.JLabel();
        jtf_numero1 = new javax.swing.JTextField();
        jtf_numero2 = new javax.swing.JTextField();
        jl_message = new javax.swing.JLabel();
        jb_suma = new javax.swing.JButton();
        jb_resta = new javax.swing.JButton();
        jb_division = new javax.swing.JButton();
        jb_multiplicacion = new javax.swing.JButton();
        jb_modulo = new javax.swing.JButton();
        jtf_resultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_titulo.setBackground(new java.awt.Color(255, 204, 204));
        jl_titulo.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_titulo.setText("Calculadora");

        jl_numero1.setBackground(new java.awt.Color(255, 204, 204));
        jl_numero1.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jl_numero1.setText("Numero 1:");

        jl_numero2.setBackground(new java.awt.Color(255, 204, 204));
        jl_numero2.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jl_numero2.setText("Numero 2:");

        jtf_numero1.setBackground(new java.awt.Color(255, 204, 204));
        jtf_numero1.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jtf_numero2.setBackground(new java.awt.Color(255, 204, 204));
        jtf_numero2.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        jl_message.setBackground(new java.awt.Color(255, 204, 204));
        jl_message.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jl_message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_message.setText("El Resultado es: ");

        jb_suma.setBackground(new java.awt.Color(255, 204, 204));
        jb_suma.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jb_suma.setText("+");

        jb_resta.setBackground(new java.awt.Color(255, 204, 204));
        jb_resta.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jb_resta.setText("-");

        jb_division.setBackground(new java.awt.Color(255, 204, 204));
        jb_division.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jb_division.setText("/");

        jb_multiplicacion.setBackground(new java.awt.Color(255, 204, 204));
        jb_multiplicacion.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jb_multiplicacion.setText("*");

        jb_modulo.setBackground(new java.awt.Color(255, 204, 204));
        jb_modulo.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jb_modulo.setText("%");

        jtf_resultado.setBackground(new java.awt.Color(255, 204, 204));
        jtf_resultado.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_message, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 73, Short.MAX_VALUE)
                        .addComponent(jb_suma)
                        .addGap(59, 59, 59)
                        .addComponent(jb_resta)
                        .addGap(61, 61, 61)
                        .addComponent(jb_multiplicacion)
                        .addGap(80, 80, 80)
                        .addComponent(jb_division)
                        .addGap(40, 40, 40)
                        .addComponent(jb_modulo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jl_numero1)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jl_numero2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_resultado, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtf_numero2))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_numero1)
                    .addComponent(jtf_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_numero2)
                    .addComponent(jtf_numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jtf_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_suma)
                    .addComponent(jb_resta)
                    .addComponent(jb_multiplicacion)
                    .addComponent(jb_division)
                    .addComponent(jb_modulo))
                .addGap(31, 31, 31)
                .addComponent(jl_message)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jb_division;
    public javax.swing.JButton jb_modulo;
    public javax.swing.JButton jb_multiplicacion;
    public javax.swing.JButton jb_resta;
    public javax.swing.JButton jb_suma;
    public javax.swing.JLabel jl_message;
    public javax.swing.JLabel jl_numero1;
    public javax.swing.JLabel jl_numero2;
    public javax.swing.JLabel jl_titulo;
    public javax.swing.JTextField jtf_numero1;
    public javax.swing.JTextField jtf_numero2;
    public javax.swing.JTextField jtf_resultado;
    // End of variables declaration//GEN-END:variables
}
